### PR TITLE
Fix sys-usb: keyerror that prevents persistent attachments on VM start.

### PR DESCRIPTION
**Pull request by Rudd-O**
Fixes https://github.com/QubesOS/qubes-issues/issues/7713 .

### CODE REVIEW

**Comment by Rudd-O** [comment]
May need to be backported to 4.1.

**Comment by Rudd-O** [comment]
Uhhh code signing check?  This is too much of an overhead for me to do.  Please take this code and pretend it's your own — I don't mind not getting credit, I just cannot be bothered to go through the code signing check.

**Comment by Rudd-O** [comment]
Bad news: the CI failed, unrelated to this change.

**Comment by Rudd-O** [comment]
No updates on this?

**Review by marmarek — APPROVED** [review]

**Pull request merged**
